### ISSUE TITLE
redirecionamento errado de link da visualizacao

### ISSUE THREAD

**Issue by maffei2443** [UnB-CIC/ml-kaggle#11]
Links do notebook [de visualização](https://github.com/UnB-CIC/ml-kaggle/blob/master/python/visualizacao.ipynb) redirecionam para páginas do tipo **https://render.githubusercontent.com/view/visualizacao/**.
Comportamento esperado: redireceionar para os notebooks especificados, assim como acontece quando 
executa-se o jupyter localmente.

**Comment by gnramos** [comment]
O link, corretamente, é relativo ao notebook. A URL gerada na visualização dentro do GItHuB é comportamento padrão do site para renderizar o notebook como página HTML.
